name: Pipeline

on:
  push:
    branches: [ develop ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install
        run: |
          npm install
      
      - name: Build
        run: |
          npm run build

      - name: Git
        run: |
          git config --global user.name 'Nicholas Panella'
          git config --global user.email 'nickjpanella@gmail.com'

      - name: NPM
        run: |
          echo //registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN} > .npmrc
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      
      - name: Pull,
        run: |
          git pull
          
      - name: Publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run ci:publish
  docs:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install
        run: |
          npm install

      - name: Generate
        run: |
          npm run docs

      - name: LS
        run: |
          ls

      - name: Status
        run: |
          git status

      - name: Pull
        run: |
          git pull
          
      - name: Commit
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Nicholas Panella
          author_email: nickjpanella@gmail.com
          message: "docs: Generated documentation"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
