name: Package Manager

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install
        run: |
          npm install
      
      - name: Build
        run: |
          npm run build

      - name: Git
        run: |
          git config --global user.name 'Nicholas Panella'
          git config --global user.email 'nickjpanella@gmail.com'

      - name: NPM
        run: |
          echo //registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN} > .npmrc
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      
      - name: Publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run ci:publish
