name: Documentation

on:
  push:
    branches: [ develop ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install
        run: |
          npm install

      - name: Generate
        run: |
          npm run docs

      - name: LS
        run: |
          ls

      - name: Status
        run: |
          git status

      - name: Pull
        run: |
          git pull
          
      - name: Commit
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Nicholas Panella
          author_email: nickjpanella@gmail.com
          message: "docs: Generated documentation"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}